# Generated by Django 4.2.25 on 2025-10-27 09:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('familytree', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='GrampsImport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Name for this import', max_length=100)),
                ('gramps_file', models.FileField(upload_to='gramps_imports/')),
                ('imported_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
