# Generated by Django 4.2.25 on 2025-10-27 09:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('familytree', '0002_grampsimport'),
    ]

    operations = [
        migrations.CreateModel(
            name='Media',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('gramps_id', models.CharField(max_length=50, unique=True)),
                ('file_path', models.CharField(max_length=255)),
                ('mime_type', models.CharField(blank=True, max_length=100)),
                ('description', models.TextField(blank=True)),
            ],
        ),
    ]
