# Generated by Django 4.2.25 on 2025-10-27 21:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('familytree', '0003_media'),
    ]

    operations = [
        migrations.AddField(
            model_name='person',
            name='media',
            field=models.ManyToManyField(blank=True, related_name='persons', to='familytree.media'),
        ),
    ]
