# Generated by Django 4.2.25 on 2025-10-28 07:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('familytree', '0005_person_is_deceased'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='type',
            field=models.CharField(choices=[('birth', 'Naissance'), ('death', 'Décès'), ('marriage', 'Mariage'), ('divorce', 'Divorce'), ('baptism', 'Baptême'), ('burial', 'Enterrement')], max_length=20),
        ),
        migrations.AlterField(
            model_name='person',
            name='gender',
            field=models.CharField(choices=[('M', 'Homme'), ('F', 'Femme'), ('U', 'Inconnu')], default='U', max_length=1),
        ),
        migrations.CreateModel(
            name='FamilyChild',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.PositiveIntegerField(default=0, help_text="Ordre de l'enfant dans la famille (depuis Gramps)")),
                ('child', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='familytree.person')),
                ('family', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='familytree.family')),
            ],
            options={
                'ordering': ['order', 'child__birth_date'],
                'unique_together': {('family', 'child')},
            },
        ),
        migrations.RemoveField(
            model_name='family',
            name='children',
        ),
        migrations.AddField(
            model_name='family',
            name='children',
            field=models.ManyToManyField(blank=True, related_name='child_families', through='familytree.FamilyChild', to='familytree.person'),
        ),
    ]
