# Generated by Django 4.2.25 on 2025-10-28 08:50

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('familytree', '0006_alter_event_type_alter_person_gender_familychild_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProposedModification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(choices=[('add', 'Ajouter'), ('update', 'Modifier'), ('delete', 'Supprimer')], max_length=10)),
                ('entity_type', models.CharField(choices=[('spouse', 'Époux/Épouse'), ('child', 'Enfant'), ('parent', 'Parent'), ('sibling', 'Frère/Sœur'), ('other', 'Autre')], max_length=50)),
                ('entity_id', models.CharField(blank=True, help_text='ID Gramps de la personne pour modification/suppression', max_length=255)),
                ('data', models.JSONField(default=dict, help_text='Les données à ajouter/modifier')),
                ('status', models.CharField(choices=[('proposed', 'Proposée'), ('acknowledged', 'Prise en compte'), ('completed', 'Complétée'), ('rejected', 'Rejetée')], default='proposed', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('admin_notes', models.TextField(blank=True, help_text='Notes lors du traitement dans Gramps')),
                ('person', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='modification_proposals', to='familytree.person')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [
                    models.Index(fields=['status', '-created_at'], name='familytree__status_f7a1d_idx'),
                ],
            },
        ),
    ]
