# Generated by Django 4.2.25 on 2025-10-29 00:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('familytree', '0008_person_timestamps'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='proposedmodification',
            new_name='familytree__status_b18c56_idx',
            old_name='familytree__status_f7a1d_idx',
        ),
    ]
