# Generated by Django 4.2.25 on 2025-10-29 00:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('familytree', '0009_rename_familytree__status_f7a1d_idx_familytree__status_b18c56_idx'),
    ]

    operations = [
        migrations.AddField(
            model_name='person',
            name='gramps_last_updated',
            field=models.DateTimeField(blank=True, help_text='Dernière modification dans Gramps', null=True),
        ),
    ]
