# Generated by Django 4.2.25 on 2026-01-05 11:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('familytree', '0010_person_gramps_last_updated'),
    ]

    operations = [
        migrations.AlterField(
            model_name='familychild',
            name='order',
            field=models.PositiveIntegerField(default=0, help_text='Child order in family (from Gramps)'),
        ),
        migrations.AlterField(
            model_name='person',
            name='gramps_last_updated',
            field=models.DateTimeField(blank=True, help_text='Last update from Gramps', null=True),
        ),
        migrations.AlterField(
            model_name='person',
            name='is_deceased',
            field=models.BooleanField(default=False, help_text='Mark as deceased even without date'),
        ),
        migrations.AlterField(
            model_name='proposedmodification',
            name='admin_notes',
            field=models.TextField(blank=True, help_text='Notes when processing in Gramps'),
        ),
        migrations.AlterField(
            model_name='proposedmodification',
            name='data',
            field=models.JSONField(default=dict, help_text='Data to add/modify'),
        ),
        migrations.AlterField(
            model_name='proposedmodification',
            name='entity_id',
            field=models.CharField(blank=True, help_text='Gramps ID of person for update/deletion', max_length=255),
        ),
    ]
