# Generated by Django 4.2.25 on 2026-01-06 12:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('familytree', '0012_add_person_indexes_and_update_help_text'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='person',
            new_name='familytree__gramps__6fbaac_idx',
            old_name='familytree_gramps__idx',
        ),
        migrations.RenameIndex(
            model_name='person',
            new_name='familytree__last_na_c9d5d7_idx',
            old_name='familytree_name_idx',
        ),
        migrations.RenameIndex(
            model_name='person',
            new_name='familytree__gramps__3b52a2_idx',
            old_name='familytree_gramps_sync_idx',
        ),
    ]
